//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int clientePK { get; set; }
        public string nome { get; set; }
        public string morada { get; set; }
        public string localidade { get; set; }
        public string codigoPostal { get; set; }
        public string NIF { get; set; }
    }
}
