//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webFinal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class dbWebFinalEntities : DbContext
    {
        public dbWebFinalEntities()
            : base("name=dbWebFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
    
        public virtual int adicionaCliente(string nome, string morada, string localidade, string codPostal, string nIF)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            var moradaParameter = morada != null ?
                new ObjectParameter("morada", morada) :
                new ObjectParameter("morada", typeof(string));
    
            var localidadeParameter = localidade != null ?
                new ObjectParameter("localidade", localidade) :
                new ObjectParameter("localidade", typeof(string));
    
            var codPostalParameter = codPostal != null ?
                new ObjectParameter("codPostal", codPostal) :
                new ObjectParameter("codPostal", typeof(string));
    
            var nIFParameter = nIF != null ?
                new ObjectParameter("NIF", nIF) :
                new ObjectParameter("NIF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("adicionaCliente", nomeParameter, moradaParameter, localidadeParameter, codPostalParameter, nIFParameter);
        }
    
        public virtual int editaCliente(Nullable<int> clienteID, string nome, string morada, string localidade, string codPostal, string nIF)
        {
            var clienteIDParameter = clienteID.HasValue ?
                new ObjectParameter("clienteID", clienteID) :
                new ObjectParameter("clienteID", typeof(int));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            var moradaParameter = morada != null ?
                new ObjectParameter("morada", morada) :
                new ObjectParameter("morada", typeof(string));
    
            var localidadeParameter = localidade != null ?
                new ObjectParameter("localidade", localidade) :
                new ObjectParameter("localidade", typeof(string));
    
            var codPostalParameter = codPostal != null ?
                new ObjectParameter("codPostal", codPostal) :
                new ObjectParameter("codPostal", typeof(string));
    
            var nIFParameter = nIF != null ?
                new ObjectParameter("NIF", nIF) :
                new ObjectParameter("NIF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editaCliente", clienteIDParameter, nomeParameter, moradaParameter, localidadeParameter, codPostalParameter, nIFParameter);
        }
    
        public virtual int eliminaCliente(Nullable<int> clienteID)
        {
            var clienteIDParameter = clienteID.HasValue ?
                new ObjectParameter("clienteID", clienteID) :
                new ObjectParameter("clienteID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("eliminaCliente", clienteIDParameter);
        }
    }
}
